### ISSUE TITLE
install worked but..

### ISSUE THREAD

**Issue by rossman22590** [replicate/zoo#22]
error getting predictions for submission id  {
  code: '42P01',
  details: null,
  hint: null,
  message: 'relation "public.predictions" does not exist'
}

I put in Supabase stuff but where is database to paste into supabase?

**Comment by cbh123** [comment]
Ah yes, I'm working now on this! For the time being, you'd have to create a supabase account with a predictions table and add that to your .env. But I'm working on fixing that within a day or two. 

https://github.com/replicate/zoo/issues/19

**Comment by cbh123** [comment]
Ok I just fixed it! Let me know if you have any issues
https://github.com/replicate/zoo/pull/23

**Comment by rossman22590** [comment]
ok but where do i paste into supabase?my db is empty

**Comment by rossman22590** [comment]
whats in this? predictions

**Comment by rossman22590** [comment]
i filled this in env 

SUPABASE_SERVICE_ROLE=
SUPABASE_URL=
SUPABASE_JWT=
SUPABASE_KEY=

then added predictions table to supabase

**Comment by rossman22590** [comment]
![image](https://github.com/replicate/zoo/assets/6137292/f8e0aa8d-08a8-4b07-bc3e-036bfcf88227)

**Comment by rossman22590** [comment]
supabase error : GET
404
/rest/v1/predictions?select=*&submission_id=eq.a-mid-nineteenth-century-engraving-of-ocean-waves-art-informel-by-frank-barrington-craig-collage-style-joseba-elorza-vv46oqn&order=created_at.asc
{
 "select": "*",
 "submission_id": "eq.a-mid-nineteenth-century-engraving-of-ocean-waves-art-informel-by-frank-barrington-craig-collage-style-joseba-elorza-vv46oqn",
 "order": "created_at.asc"
}
