### ISSUE TITLE
zoo.replicate.dev site stopped working

### ISSUE THREAD

**Issue by samitkumarsinha** [replicate/zoo#48]
Entering the website welcomes us with an awe inspiring bone chilling ominous message:

Application error: a client-side exception has occurred (see the browser console for more information).

Can anyone please look into the matter

**Comment by samitkumarsinha** [comment]
The problem wont fixed, As usual It is not working.

**Comment by cbh123** [comment]
Working on it!

**Comment by samitkumarsinha** [comment]
Thanks

**Comment by samitkumarsinha** [comment]
Still the same error. It will take a long time I guess

**Comment by cbh123** [comment]
Ok sorry for the delay! Now it's much much faster. I set an index on the submissions_id column
